package standards

func DefaultCatalog() []Standard {
	return []Standard{
		{
			Code:            "NBR-5410",
			Title:           "Instalações elétricas de baixa tensão",
			Domain:          "eletrica",
			Subject:         "instalacoes eletricas",
			Version:         "catalog-2026.04",
			Status:          StandardStatusActive,
			SourceType:      SourceTypeNormative,
			SourceName:      "ABNT NBR 5410",
			HierarchyWeight: WeightForSourceType(SourceTypeNormative),
			AppliesTo:       []string{"projects", "calculations", "conformidade"},
		},
		{
			Code:            "NR-10",
			Title:           "Segurança em instalações e serviços em eletricidade",
			Domain:          "seguranca",
			Subject:         "seguranca eletrica",
			Version:         "catalog-2026.04",
			Status:          StandardStatusActive,
			SourceType:      SourceTypeRegulation,
			SourceName:      "NR-10",
			HierarchyWeight: WeightForSourceType(SourceTypeRegulation),
			AppliesTo:       []string{"projects", "conformidade", "reports"},
		},
		{
			Code:            "NBR-ISO-CIE-8995-1",
			Title:           "Iluminação de ambientes de trabalho - Parte 1: Interior",
			Domain:          "iluminacao",
			Subject:         "iluminancia e iluminacao interna",
			Version:         "catalog-2026.04",
			Status:          StandardStatusActive,
			SourceType:      SourceTypeNormative,
			SourceName:      "ABNT NBR ISO/CIE 8995-1",
			HierarchyWeight: WeightForSourceType(SourceTypeNormative),
			AppliesTo:       []string{"projects", "calculations", "conformidade"},
		},
		{
			Code:            "LEI-5194-1966",
			Title:           "Regulamenta o exercício das profissões de Engenheiro, Arquiteto e Engenheiro-Agrônomo",
			Domain:          "profissional",
			Subject:         "responsabilidade tecnica",
			Version:         "catalog-2026.04",
			Status:          StandardStatusActive,
			SourceType:      SourceTypeLaw,
			SourceName:      "Lei 5.194/1966",
			HierarchyWeight: WeightForSourceType(SourceTypeLaw),
			AppliesTo:       []string{"conformidade", "reports"},
		},
		{
			Code:            "LEI-6496-1977",
			Title:           "Institui a Anotação de Responsabilidade Técnica",
			Domain:          "profissional",
			Subject:         "art",
			Version:         "catalog-2026.04",
			Status:          StandardStatusActive,
			SourceType:      SourceTypeLaw,
			SourceName:      "Lei 6.496/1977",
			HierarchyWeight: WeightForSourceType(SourceTypeLaw),
			AppliesTo:       []string{"conformidade", "reports"},
		},
	}
}
